ixpantia/faucet

examples/plumber_in_packages/Dockerfile, examples/plumber_in_packages/entrypoint.R, mkdocs/docs/en/examples.md, mkdocs/docs/es/examples.md, mkdocs/mkdocs.yml
=> docs: Adds example of Plumber in an R Package

Cargo.lock, Cargo.toml, README.md, examples/plumber_in_packages/Dockerfile, mkdocs/docs/en/examples.md, mkdocs/docs/en/in_containers.md, mkdocs/docs/en/install.md, mkdocs/docs/es/examples.md, mkdocs/docs/es/in_containers.md, mkdocs/docs/es/install.md, mkdocs/mkdocs.yml
=> chore: Switches repos to ixpantia

Cargo.lock, Cargo.toml, src/client/worker.rs, src/main.rs
=> feat: Improves Ctrl-C exit strategy

src/cli.rs, src/client/load_balancing/ip_hash.rs, src/client/pool.rs, src/client/websockets.rs, src/client/worker.rs, src/networking.rs, src/server/mod.rs, src/server/service.rs
=> Improves usage for Windows

src/client/worker.rs
=> feat: Adds FAUCET_WORKER_ID environment variable

src/client/websockets.rs, src/error.rs
=> fix: Fixes panic on windows with Ctrl-C

docs/en/reverse_proxy.md, docs/es/reverse_proxy.md
=> Add proxy_http_version in nginx documentation

Cargo.lock, Cargo.toml, mkdocs.yml, src/http.rs, src/lib.rs
=> Update dependencies and semver

docs/es/getting_started.md, docs/es/index.md
=> Documentación Router

CONTRIBUTING.md, README.md
=> docs: Creates a contributing.md document

src/cli.rs
=> fix: Fixes naming conflict for CLI arguments

README.md
=> 1.0.0 alpha

Cargo.lock, Cargo.toml, src/client/load_balancing/ip_hash.rs, src/client/load_balancing/mod.rs, src/client/load_balancing/round_robin.rs, src/client/pool.rs, src/error.rs
=> chore: Improves performance by removing async-trait

src/client/websockets.rs
=> chore: Removes allocation for SEC WebSockets

Cargo.lock, Cargo.toml, src/cli.rs, src/client/load_balancing/ip_hash.rs, src/client/load_balancing/mod.rs, src/client/pool.rs, src/client/websockets.rs, src/client/worker.rs, src/global_conn.rs, src/lib.rs, src/main.rs, src/server/mod.rs
Adds graceful shutdowns on Unix systems
=> Graceful shutdown

.github/workflows/release.yaml, Cargo.lock, Cargo.toml, README.md, docs/en/options.md, docs/es/options.md, examples/plumber_in_packages/Dockerfile, mkdocs.yml, src/cli.rs, src/lib.rs, src/main.rs, src/shutdown.rs
=> chore: Adds CLI arg for shutdown strategy

.gitignore, Cargo.lock, Cargo.toml, examples/quarto/.gitignore, examples/quarto/example.qmd, src/cli.rs, src/main.rs, src/server/logging.rs, src/server/onion.rs
Using the environment variable `FAUCET_MAX_LOG_FILE_SIZE` will rotate the log file when the size of the file reaches the specified value.
Closes #163
=> Adds max log file and log file rotation

.gitignore, Cargo.lock, Cargo.toml, src/main.rs
=> feat: Reads Renviron on root of Working Dir

.github/workflows/nightly.yaml, .github/workflows/release.yaml
=> feat: Adds image build for R4.5

Cargo.toml, src/client/websockets.rs, src/client/worker.rs, src/error.rs, src/networking.rs
=> fix: Fixes port assign range for plumber

Cargo.lock, Cargo.toml, examples/shiny/app.R, examples/shiny/www/reconnect.js, src/client/websockets.rs, src/client/worker.rs, src/error.rs, src/main.rs, src/server/mod.rs, src/server/reconnect.js, src/server/service.rs
*   **`ReconnectingWebSocket` Class:** A new JavaScript wrapper for the native `WebSocket` API has been implemented.
*   **Automatic Reconnection:** It automatically attempts to re-establish a connection if it's unexpectedly dropped. Reconnection attempts and delays are configurable.
*   **Session ID Generation:** Upon initialization, it generates a unique `sessionId` (using `crypto.randomUUID` with a fallback) and appends it as a query parameter to the WebSocket URL.
*   **Event Hooks:** Provides `onreconnect` and other standard WebSocket event handlers for better integration.
*   **Integration with Shiny:** The `Shiny.createSocket` function is updated to use this new `ReconnectingWebSocket` class, enabling this feature across the application.
---
The server has been significantly …
=> feat: Adds reconnect logic for Shiny sessions

CHANGELOG.md, Cargo.lock, Cargo.toml, src/client/websockets.rs
=> fix: Fixes query param detection in case insensitive form
